#!/bin/bash

set -e
shopt -s nullglob

if [ "$#" -eq 0 ]; then
  mp3=( ~/Music/mp3* )
else
  mp3=( "$@" )
fi

artists=() n_albums=0 n_tracks=0

for dir in "${mp3[@]}"; do
  for artist in "$dir"/*/; do
    for album in "$artist"/*/; do
      for track in "$album"/*.mp3; do
        (( ++n_tracks ))
      done
      (( ++n_albums ))
    done
    artists+=( "$( basename "$artist" )" )
  done
done

n_artists="$(
  for x in "${artists[@]}"; do echo "$x"; done | sort | uniq | wc -l
)"

printf '%d artists - %d albums - %d tracks\n' \
  "$n_artists" "$n_albums" "$n_tracks"
